---
title: "ci"
output: html_document
date: "2023-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(tidyverse)
```

```{r}
set.seed(2023)
simdata = function(n, distribution,b1,lambda=0.5, gamma=2,alpha=2) {
  exponential = function(u, x, lambda, b1) {
    time = -log(u) / (exp(x * b1) * lambda) }  
  weibull = function(u, x, lambda, gamma, b1) {
    time = ( -log(u) / (exp(x * b1) * lambda) ) ^ (1 / gamma) }
  gompertz = function(u, x, lambda, alpha, b1) {
    time = (1/alpha) * log( 1 - (alpha * log(u) / (lambda * exp(b1 * x))) ) }
  x = rbinom(n, 1, 0.5)
  u = runif(n)
  if (distribution == "exponential") {
    time = exponential(u, x, lambda, b1) } 
  else if (distribution == "weibull") {
    time = weibull(u, x, lambda, gamma,b1) }
  else { 
    time = gompertz(u, x, lambda, alpha, b1) } 
  
  time[time < 1/365] = 1/365
  time[time == 1 / 365] = time[time == 1 / 365] + rnorm(length(time[time == 1 / 365]), 0, 1e-4)
  time = abs(time)
  e=as.numeric(time<5)
  time=pmin(time,5)
  
  # data set
  survival_data = data.frame(id=1:n,
                             time = time,
                             x = x,
                             event=e)
}
```

```{r}
set.seed(2023)
simulate = function(sim, n, b1, dist = "gompertz") {
  # Set up coefficient vectors
  exp_beta = rep(NA, sim)
  weibull_beta = rep(NA, sim)
  gompertz_beta = rep(NA, sim)
  
 
    
    for (i in 1:sim) {
      
      data = simdata(n, distribution = dist,b1, 
                           lambda = 0.5, gamma = 2,alpha=2)
      
      fit.exponential = survreg(Surv(data$time, data$event) ~ data$x, 
                                dist = "exponential") 
      fit.weibull = survreg(Surv(data$time, data$event) ~ data$x, 
                            dist = "weibull")
      fit.gompertz = coxph(Surv(data$time, data$event) ~ data$x)
      
       
      exp_beta[i] = -fit.exponential$coefficients[-1]
      weibull_beta[i] = -fit.weibull$coefficients[-1] / fit.weibull$scale
      gompertz_beta[i] = fit.gompertz$coefficients[1]
      
    }
    
   
  
  coef = tibble(exp = exp_beta,
                weibull = weibull_beta,
                gompertz=gompertz_beta)
  
  return(coef) }

```

```{r}
t1=simulate(1000,400,2)
lower_ci=quantile(t1$gompertz,0.025)
lower_ci
upper_ci=quantile(t1$gompertz,0.975)
upper_ci


```
