---
title: "p8160 project1"
author: "Ruihan Zhang"
date: "2023-02-19"
output: html_document
---

```{r}
library(tidyverse)
library(caret)
library(survival)
library(simsurv)
```
```{r}
set.seed(2023)
n=1000
simulation_data = function(n, p, lambdas, gammas  ) {
  
  x1=rbinom(n,1,0.5)
  u = runif(n)
  expo = runif(n) < p 
  covariate <- rexp(n, rate = lambda)
  # generating exponential data
  exponential =  simsurv(dist = "exponential", lambdas = 0.1, gammas = 0.05, x = covariate, betas = 2, maxt = 5 )
  time = -log(u) / (exp(x * b1) * lambdas)
  # generating Weibull data
  weibull = simsurv(dist = "weibull", lambdas = 0.1, gammas = 0.05, x = covariate, betas = 2, maxt = 5)
  time = ( -log(u) / (exp(x * b1) * lambdas) ) ** (1 / gammas)
  
  if (time<1/365){
    time[time < 1/365]=1/365
  }
  else{
     time[time == 1 / 365] = time[time == 1 / 365] + rnorm(length(time[time == 1 / 365]), 0, 1e-4)
  }
  
 
  time = abs(time)
  
  e = as.numeric(time < 5)
  time = pmin(time, 5)
  
  name = paste("n =", n, ", p =", p)
  
  return(tibble(name = name, time = time, event = e, x1 = x1))

}
```

```{r}
fit_exp = function(df) {
  fit.exponential = survreg(Surv(time, event) ~ x1, dist = "exponential", data = df)
  return(as.numeric(-fit.exponential$coefficients[-1]))
}
fit_weibull = function(df) {
  fit.weibull <- survreg(Surv(time, event) ~ x1, dist = "weibull", data = df)
  return(as.numeric(-fit.weibull$coefficients[-1] / fit.weibull$scale))
}
fit_cox = function(df) {
  fit.cox <- coxph(Surv(time, event) ~ x1, data = df)
  return(as.numeric(fit.cox$coefficients))
}
```





