---
title: "t"
output: html_document
date: "2023-02-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "group project"
author: "Ruihan Zhang"
date: "2023-02-20"
output: github_document
---

 ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(tidyverse)
```

```{r}
set.seed(2023)
simdata = function(n, distribution,b1,lambda=0.5, gamma=2,alpha=0.5) {
  exponential = function(u, x, lambda, b1) {
    time = -log(u) / (exp(x * b1) * lambda) }  
  weibull = function(u, x, lambda, gamma, b1) {
    time = ( -log(u) / (exp(x * b1) * lambda) ) ^ (1 / gamma) }
  gompertz = function(u, x, lambda, alpha, b1) {
    time = (1/alpha) * log( 1 - (alpha * log(u) / (lambda * exp(b1 * x))) ) }
  x = rbinom(n, 1, 0.5)
  u = runif(n)
  if (distribution == "exponential") {
    time = exponential(u, x, lambda, b1) } 
  else if (distribution == "weibull") {
    time = weibull(u, x, lambda, gamma,b1) }
  else { 
    time = gompertz(u, x, lambda, alpha, b1) } 
  
  time[time < 1/365] = 1/365
  time[time == 1 / 365] = time[time == 1 / 365] + rnorm(length(time[time == 1 / 365]), 0, 1e-4)
  time = abs(time)
  e=as.numeric(time<5)
  time=pmin(time,5)
  
  # data set
  survival_data = data.frame(id=1:n,
                             time = time,
                             x = x,
                             event=e)
}
```

```{r}
set.seed(2023)
simulate = function(sim, n, b1, dist = "weibull") {
  # Set up coefficient vectors
  exp_beta = rep(NA, sim)
  weibull_beta = rep(NA, sim)
  gompertz_beta = rep(NA, sim)
  
 
    
    for (i in 1:sim) {
      
      data = simdata(n, distribution = dist,b1, 
                           lambda = 0.5, gamma = 2,alpha=2)
      
      fit.exponential = survreg(Surv(data$time, data$event) ~ data$x, 
                                dist = "exponential") 
      fit.weibull = survreg(Surv(data$time, data$event) ~ data$x, 
                            dist = "weibull")
      fit.gompertz = coxph(Surv(data$time, data$event) ~ data$x)
      
       
      exp_beta[i] = -fit.exponential$coefficients[-1]
      weibull_beta[i] = -fit.weibull$coefficients[-1] / fit.weibull$scale
      gompertz_beta[i] = fit.gompertz$coefficients[1]
      
    }
    
   
  
  coef = tibble(exp = exp_beta,
                weibull = weibull_beta,
                gompertz=gompertz_beta)
  
  exp_bias = (sum(exp_beta - b1)) / sim 
  weibull_bias = (sum(weibull_beta - b1)) / sim
  gompertz_bias = (sum(gompertz_beta - b1)) / sim
  exp_MSE = (sum((b1 - exp_beta)^2)) / sim
  weibull_MSE = (sum((b1 - weibull_beta)^2)) / sim
  gompertz_MSE = (sum((b1 - gompertz_beta)^2)) / sim
  exp_var=var(exp_beta)
  weibull_var=var(weibull_beta)
  gompertz_var=var(gompertz_beta)
  char = tibble(model = c("exp", "weibull","cox"),
                bias=c(exp_bias,weibull_bias,gompertz_bias),
                mse = c(exp_MSE, weibull_MSE, gompertz_MSE),
                variance=c(exp_var,weibull_var,gompertz_var))
  
  results = list(coef, char)
  names(results) = c("coefficients", "performance")
  return(results)
  }
  

```


```{r, echo=FALSE, warning=FALSE, fig.height=4.3}
set.seed(2023)
sim_results = 
  tibble(sample_size = c(100,150,200,250,300,350,400)) %>% 
  mutate(
    output= map(.x = sample_size, ~simulate(sim = 1000, n = .x, b1 = 2, 
                                                        dist = "weibull")$performance),
                output = map(.x = output, ~mutate(.x)))
temp1 = sim_results %>% unnest(output)
```


```{r}
weibull_bias=ggplot(temp1, aes(x = sample_size, y = bias, color = model)) +
  geom_point(size = 1) +
  geom_line(size = 1) +
  xlab("sample size") +
  labs(
       title="Sample size vs Bias by Survival Model") + 
  theme(plot.caption = element_text(hjust = 0.5, size = rel(1.2)))
weibull_bias
ggsave(file="results/weibull_bias.pdf",width=8,height=5)

```


```{r}
weibull_var=ggplot(temp1, aes(x = sample_size, y = variance, color = model)) +
  geom_point(size = 1) +
  geom_line(size = 1) +
  xlab("sample size") +
  labs(
       title="Sample size vs Variance by Survival Model") + 
  theme(plot.caption = element_text(hjust = 0.5, size = rel(1.2)))
qwibull_var
ggsave(file="results/weibull_var.pdf",width=8,height=5)
```